BhartiManagementSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('', include('crm.urls')),
    path('cdb/', include('cdb.urls')),
    path('demo/', include('demo.urls')),
    path('tp/', include('tp.urls')),
    path('sys/admin/', include('sysadmin.urls')),
    path('products/', include('productlist.urls')),
] + debug_toolbar_urls() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='tp_index_view'),
    path('manager/', views.manager_index_view_initial, name='tp_manager_index_view_initial'),
    path('manager/<int:subordinate_id>', views.manager_index_view_for_subordinate, name='tp_manager_index_view_for_subordinate'),
    path('update/<int:entry_id>/<str:field_name>', views.update_field, name='update_field'),
    path('edit/<int:entry_id>/<str:field_name>', views.edit_field, name='edit_field'),
    path('entry/add/crm', views.add_entry_from_crm, name='tp_add_entry_from_crm'),
    path('entry/add/cdb', views.add_entry_from_cdb, name='tp_add_entry_from_cdb'),
    path('popover-content/<int:entry_id>/', views.tp_popover_content, name='tp_popover_content'),
    path('toggle/not_visited/<int:entry_id>/', views.tp_toggle_not_visited, name="tp_toggle_not_visited"),
]

crm/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from base.models import Setting, Brochure
from decimal import Decimal


class Sector(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

        
class Discipline(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

        
class HospitalType(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=150, unique=True)
    code = models.CharField(max_length=2, unique=True)
    
    def __str__(self):
        return self.name

class District(models.Model):
    name = models.CharField(max_length=150)
    state = models.ForeignKey(State, on_delete=models.CASCADE, related_name='districts')

    def __str__(self):
        return self.name
    
    class Meta:
        unique_together = ['name', 'state']
        ordering = ['state']
    

class Area(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE, related_name='areas')
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['district']


class StageGroup(models.Model):
    name = models.CharField(max_length=100, unique=True)
    order = models.IntegerField()
    text_color = models.CharField(max_length=7, default="#ffffff")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order']

class Stage(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=500)
    win = models.PositiveIntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(100),
        ]
    )

    group = models.ForeignKey(StageGroup, related_name='stages', on_delete=models.SET_NULL, null=True, blank=True)
    tracks_tp_link = models.BooleanField(default=False, verbose_name="Track for TP?")

    order = models.IntegerField(
        default=0, 
        help_text='Set the order for this stage.'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order']


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)
    text_color = models.CharField(max_length=7, default="#ffffff")
    order = models.IntegerField(
        default=0,
        help_text='Set the order for this product category.',
    )

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['order']
        verbose_name_plural = 'Categories'


class Product(models.Model):
    limiter = 100000
    name = models.CharField(max_length=150, unique=True)
    quoted_price = models.PositiveBigIntegerField(verbose_name='Quoted Price')
    cutoff = models.PositiveBigIntegerField(verbose_name='Cutoff (Incl. GST)')
    purchase_price = models.PositiveBigIntegerField(verbose_name='Purchase Price')
    dealer_price = models.PositiveBigIntegerField(verbose_name='Sub Dealer Price')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    brochure = models.ForeignKey(Brochure, blank=True, null=True, on_delete=models.SET_NULL, related_name='related_products')

    def va_percentage(self):
        if self.purchase_price == 0:
            return "UNDEFINED"
        return str(round(((self.cutoff - self.purchase_price) / self.purchase_price) * 100)) + '%'
    
    def gross_va(self):
        return round((self.cutoff - self.purchase_price) / self.limiter, 1)
    
    def net_va(self):
        return round(self.gross_va() / 2, 1)

    def incentive(self):
        return round((self.cutoff - self.purchase_price) * (5 / 100))

    def employee_incentive(self):
        return round(self.incentive() * float(Setting.objects.get(key='EMPLOYEE_INCENTIVE').value))

    def manager_incentive(self):
        return round(self.incentive() * float(Setting.objects.get(key='MANAGER_INCENTIVE').value))

    def va(self):
        return self.net_va()

    def __str__(self):
        return self.name

    va_percentage.short_description = "VA%"

    class Meta:
        ordering = ['category', 'name']


class Configuration(models.Model):
    name = models.CharField(max_length=150)
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='configurations')

    
class Entry(models.Model):
    EXPECTED_CHOICES = [
        ('-2', 'N/A'),
        ('-1', 'BEYOND'),
        ('0', 'JAN'),
        ('1', 'FEB'),
        ('2', 'MAR'),
        ('3', 'APR'),
        ('4', 'MAY'),
        ('5', 'JUN'),
        ('6', 'JUL'),
        ('7', 'AUG'),
        ('8', 'SEP'),
        ('11', 'OCT'),
        ('9', 'NOV'),
        ('10', 'DEC'),
    ]
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='entry')
    institute = models.CharField(max_length=200)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    landmark = models.CharField(max_length=300, blank=True)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    discipline = models.ForeignKey(Discipline, on_delete=models.CASCADE)
    hospital_type = models.ForeignKey(HospitalType, on_delete=models.CASCADE)
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE)
    expected = models.CharField(max_length=2, choices=EXPECTED_CHOICES)
    products = models.ManyToManyField(Product, through='ProductEntry', related_name='entries')
    notes = models.CharField(max_length=2000, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    has_been_booked = models.BooleanField(default=False)
    has_been_executed = models.BooleanField(default=False)
    is_in_demo = models.BooleanField(default=False)
    has_been_sent_to_tp = models.BooleanField(default=False)

    def yet_to_be_contacted(self):
        if self.stage.group and self.stage.group.name == 'BIRD':
            if self.created_on < timezone.now() - datetime.timedelta(days=2):
                return True
        return False

    def yet_to_be_sent_to_tp(self):
        if self.stage.tracks_tp_link == True and self.has_been_sent_to_tp == True:
            return False
        elif self.stage.tracks_tp_link == True and self.has_been_sent_to_tp == False:
            return True
        else:
            return False

    def is_in_tp(self, owner_id):
        from tp.models import TPEntry
        if self.stage.tracks_tp_link == False: # Because then don't care
            print("Stopped Caring")
            return True
        if self.stage.tracks_tp_link == True:
            if TPEntry.objects.filter(owner=owner_id, type=TPEntry.CRM, link=self.pk).exists():
                print("Legit Shit!?")
                return True
        return False 

    def va(self):
        total_value = sum(product_entry.count * product_entry.product.va() for product_entry in self.product_entries.all())
        return total_value

    def booking_va(self):
        total_value = 0
        for product_entry in self.product_entries.all():
            if product_entry.has_booking:
                if product_entry.booking_count and product_entry.booking_va:
                    total_value += (product_entry.booking_count * product_entry.booking_va)
                elif product_entry.booking_count and product_entry.booking_va == None:
                    total_value += (product_entry.booking_count * product_entry.product.va())
                elif product_entry.booking_count == None and product_entry.booking_va:
                    total_value += (product_entry.count * product_entry.booking_va)
                else:
                    total_value += (product_entry.count * Decimal(product_entry.product.va()))
        return total_value

    def execution_va(self):
        total_value = 0
        for product_entry in self.product_entries.all():
            if product_entry.has_execution:
                if product_entry.execution_count and product_entry.execution_va:
                    total_value += (product_entry.execution_count * product_entry.execution_va)
                elif product_entry.execution_count and product_entry.execution_va == None:
                    total_value += (product_entry.execution_count * product_entry.product.va())
                elif product_entry.execution_count == None and product_entry.execution_va:
                    total_value += (product_entry.count * product_entry.execution_va)
                else:
                    total_value += (product_entry.count * Decimal(product_entry.product.va()))
        return total_value


    def time_since_creation(self):
        current_time = timezone.now()
        time_diff = current_time - self.created_on
        if time_diff < datetime.timedelta(days=1):
            return "Today"
        elif time_diff < datetime.timedelta(days=7):
            days_ago = time_diff.days
            return f"{days_ago} day{'s' if days_ago > 1 else ''} ago"
        elif time_diff < datetime.timedelta(days=365):
            months_ago = time_diff.days // 30
            if months_ago < 1:
                weeks_ago = time_diff.days // 7
                return f"{weeks_ago} week{'s' if weeks_ago > 1 else ''} ago"
            return f"{months_ago} month{'s' if months_ago > 1 else ''} ago"
        else:
            years_ago = time_diff.days // 365
            return f"{years_ago} year{'s' if years_ago > 1 else ''} ago"
        
    def __str__(self):
        return self.institute

    class Meta:
        verbose_name_plural = 'Entries'
        ordering = ['stage']


class ProductEntry(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, related_name='product_entries')

tp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import F
from .models import TPEntry
from crm.models import Entry
from crm.views import get_subordinates
from cdb.models import CDBEntry

@login_required
def manager_index_view_for_subordinate(request, subordinate_id):
    entries = TPEntry.objects.all().filter(owner=subordinate_id).order_by(F('schedule').asc(nulls_last=True), F('stage__order').asc(nulls_last=True))
    context = {
        'entries': entries,
        'subordinate_id': subordinate_id,
    }
    return render(request, 'tp/index_view.html', context)

@login_required
def manager_index_view_initial(request):
    subordinates = get_subordinates(request)

    for subordinate in subordinates:
        setattr(subordinate, 'total_entries', TPEntry.objects.filter(owner=subordinate).count())
        not_visited = TPEntry.objects.filter(owner=subordinate, not_visited=True).count()
        setattr(subordinate, 'not_visited_entries', not_visited)

    context = {
        'subordinates': subordinates
    }
    return render(request, 'tp/manager_index_initial.html', context)


def tp_toggle_not_visited(request, entry_id):
    entry = get_object_or_404(TPEntry, id=entry_id)
    entry.not_visited = not entry.not_visited
    entry.save()
    
    context = {
        'entry': entry,
    }

    return render(request, 'tp/partials/_table_row.html', context)

def edit_field(request, entry_id, field_name):
    entry = get_object_or_404(TPEntry, id=entry_id)
    context = {
        'entry': entry,
        'field_name': field_name,
        'field_value': getattr(entry, field_name),
    }
    return render(request, 'tp/includes/edit_field.html', context)

def update_field(request, entry_id, field_name):
    if request.method == 'POST':
        entry = get_object_or_404(TPEntry, id=entry_id)
        new_value = request.POST.get('value')
        setattr(entry, field_name, new_value)
        entry.save()
        
        return JsonResponse({'new_value': new_value})

def tp_popover_content(request, entry_id):
    entry = get_object_or_404(TPEntry, id=entry_id)
    popover_edit_link = reverse('admin:tp_tpentry_change', args=(entry_id,))
    try:
        crm_entry = Entry.objects.get(id=entry.link)
    except Entry.DoesNotExist:
        crm_entry = None

    try:
        cdb_entry = CDBEntry.objects.get(id=entry.link)
    except CDBEntry.DoesNotExist:
        cdb_entry = None
        
    context = {
        'entry': entry,
        'popover_edit_link': popover_edit_link,
        'is_from_crm': True if entry.type == entry.CRM else False,
        'is_from_cdb': True if entry.type == entry.CDB else False,
        'crm_entry': crm_entry,
        'cdb_entry': cdb_entry,
    }

    return render(request, 'tp/partials/_popover_content.html', context)

@login_required
def index_view(request):
    entries = TPEntry.objects.all().filter(owner=request.user).order_by(F('schedule').asc(nulls_last=True), F('stage__order').asc(nulls_last=True))
    context = {
        'entries': entries,
    }
    return render(request, 'tp/index_view.html', context)

@login_required
def edit_view(request):
    entries = TPEntry.objects.all().filter(owner=request.user).order_by(F('schedule').asc(nulls_last=True), F('stage__order').asc(nulls_last=True))
    context = {
        'entries': entries,
    }
    return render(request, 'tp/edit_view.html', context)

@login_required
def add_entry_from_crm(request):
    if request.method == 'POST':
        selected_checkboxes = request.POST.getlist('selected-checkboxes')
        
        for id in selected_checkboxes:
            entry = Entry.objects.get(id=int(id))
            new_tp_entry = TPEntry()
            new_tp_entry.owner = entry.owner
            new_tp_entry.institute = entry.institute
            new_tp_entry.area = entry.area
            new_tp_entry.landmark = entry.landmark
            new_tp_entry.sector = entry.sector
            new_tp_entry.discipline = entry.discipline
            new_tp_entry.hospital_type = entry.hospital_type
            new_tp_entry.stage = entry.stage
            new_tp_entry.type = new_tp_entry.CRM
            new_tp_entry.link = entry.id
            new_tp_entry.save()
            new_tp_entry.products.set(entry.products.all())
            new_tp_entry.save()
            entry.has_been_sent_to_tp = True
            entry.save()
        
        return redirect('tp_index_view')

    return redirect('crm_index_view')

@login_required
def add_entry_from_cdb(request):
    if request.method == 'POST':
        selected_checkboxes = request.POST.getlist('selected-checkboxes')
        
        for id in selected_checkboxes:
            entry = CDBEntry.objects.get(id=int(id))
            new_tp_entry = TPEntry()
            new_tp_entry.owner = request.user
            new_tp_entry.institute = entry.institute
            new_tp_entry.area = entry.area
            new_tp_entry.landmark = entry.landmark
            new_tp_entry.sector = entry.sector
            new_tp_entry.discipline = entry.discipline
            new_tp_entry.hospital_type = entry.hospital_type
            new_tp_entry.type = new_tp_entry.CDB
            new_tp_entry.link = entry.id
            new_tp_entry.save()
        
        return redirect('tp_index_view')

    return redirect('cdb_index_view')

tp/templates/tp/partials/_table_body.html
{% load compress %}
<tbody>
  {% if use_form %}
  <form id="tour-plan" action="{{ tour_plan_add_url }}" method="POST">
    {% csrf_token %}
  {% endif %}
  {% for entry in entries %}
  <tr class="odd:bg-white odd:dark:bg-gray-900 even:bg-gray-50 even:dark:bg-gray-800 border-b dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
    {% if use_form %}
    <td class="px-3 py-0">
    <input name="selected-checkboxes" type="checkbox" value="{{ entry.id }}" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
    </td>
    {% endif %}
    <th id="tpentry-{{ entry.id }}-institute" hx-get="{% url 'tp_popover_content' entry.id %}" hx-trigger="click" hx-target="#popover-content" hx-swap="innerHTML" hx-indicator=".htmx-indicator" scope="row" class="popover-trigger px-3 py-0 font-medium text-gray-900 whitespace-nowrap dark:text-white">
      <span class="flex {% if entry.not_visited %}text-red-800 dark:text-red-500{% endif %}">
        {{ entry.institute }}
      </span>
    </th>
    <td class="px-3 py-0">
      {{ entry.area.name }} |
      {{ entry.area.district }} |
      <span data-tooltip-target="tooltip-state-{{ entry.id }}">
        {{ entry.area.district.state.code }}
      </span>
    </td>
    {% if not hide_stage %}
    <td class="px-3 py-0">
      <span data-tooltip-target="tooltip-stage-{{ entry.id }}">
        {{ entry.stage.name }}
      </span>
      <div id="tooltip-stage-{{ entry.id }}" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white transition-opacity duration-300 bg-gray-900 rounded-lg shadow-sm opacity-0 tooltip dark:bg-gray-700">
        {{ entry.stage.description }}
        <div class="tooltip-arrow" data-popper-arrow></div>
      </div>
    </td>
    {% endif %}
    {% if not hide_win %}
    <td class="px-3 py-0">
      {% if entry.stage.win != 0 %}
      {{ entry.stage.win }}%
      {% endif %}
    </td>
    {% endif %}
    {% if not hide_expected %}
    <td class="px-3 py-0">
      {{ entry.get_expected_display }}
    </td>
    {% endif %}
    {% if not hide_total_products %}
    <td class="px-3 py-0">
      {{ entry.total_products }}
    </td>
    {% endif %}
    {% if not hide_va %}
    <td class="px-3 py-0">
      {% if entry.va is not None %}
      {{ entry.va|floatformat:1 }}
      {% endif %}
    </td>
    {% endif %}
    {% if not hide_products %}
    <td class="px-3 py-0">
      {% for product in entry.products.all %}
      <span data-popover-target="popover-{{ entry.id }}-{{ product.id }}" data-popover-placement="top" style="background-color: {{ product.category.background_color }}; color: {{ product.category.text_color }};">{{ product.name }}</span>
      <div id="popover-{{ entry.id }}-{{ product.id }}" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 tooltip">
        {{ product.count }}
        <div class="tooltip-arrow" data-popper-arrow></div>
      </div>
      {% if not forloop.last %} | {% endif %}
      {% endfor %}
    </td>
    {% endif %}
    {% if show_schedule %}
    <td hx-get="{% url 'edit_field' entry.id 'schedule' %}" hx-trigger="click" hx-target="#field-schedule-{{ entry.id }}" id="field-schedule-{{ entry.id }}" scope="col" class="px-3 py-0">
      <span>{{ entry.schedule|date:"d-m-Y" }}</span>
    </td>
    <td class="px-3 py-0">
      {{ entry.schedule|date:"l"}}
    </td>
    <td scope="col" class="px-3 py-0">
      {{ entry.schedule|date:"g:i A"}}
    </td>
    {% endif %}
    {% if show_purpose %}
    <td scope="col" class="px-3 py-0">
      <span class="{% if entry.purpose.purpose_type|upper == "VIRTUAL" %}text-green-500{% endif %}">
      {{ entry.purpose }}
      </span>
    </td>
    {% endif %}
    {% if show_owner %}
    <td scope="col" class="px-3 py-0">
      {% if entry.owner.first_name %}
      {{ entry.owner.first_name }}
      {% else %}
      {{ entry.owner.username }}
      {% endif %}
    </td>
    {% endif %}
  </tr>
{% endfor %}

{% if use_form %}
</form>
{% endif %}

<div data-popover id="popover-default" role="tooltip" class="absolute z-10 invisible inline-block w-96 text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 dark:border-gray-600 dark:bg-gray-800">
  <div id="popover-content" class="p-2">
  </div>
</div>

{% compress js %}
<script>
  document.addEventListener("htmx:beforeRequest", function() {
    const popoverContent = document.getElementById("popover-content");
    popoverContent.innerHTML = `
    <div class="flex items-center justify-center w-56 h-56 mx-auto bg-gray-50 dark:bg-gray-800">
      <div class="px-3 py-1 text-xs font-medium leading-none text-center text-blue-800 bg-blue-200 rounded-full animate-pulse dark:bg-blue-900 dark:text-blue-200">Fetching Data...</div>
    </div>
    `;
  });

  document.addEventListener('click', function (event) {
    const popoverContent = document.getElementById('popover-default');
    const triggerElements = document.getElementsByClassName('popover-trigger');
    
    let clickedInsideTrigger = false;

    // Loop through all popover-trigger elements and check if the clicked target is one of them
    for (let i = 0; i < triggerElements.length; i++) {
      if (triggerElements[i].contains(event.target)) {
        clickedInsideTrigger = true;
        
        const rect = triggerElements[i].getBoundingClientRect();

        // Set the popover's position dynamically beside the clicked <th>
        popoverContent.style.left = `${rect.right + window.scrollX + 10}px`; // 10px to the right of the <th>
        popoverContent.style.top = `${rect.top + window.scrollY}px`; // Align with the top of the <th>
        
        // Make the popover visible
        popoverContent.classList.remove('invisible', 'opacity-0');
        popoverContent.classList.add('opacity-100');
        break;
      }
    }

    // If the click happened outside the popover and not on a trigger element, hide the popover
    if (!clickedInsideTrigger && !popoverContent.contains(event.target)) {
      popoverContent.classList.add('invisible', 'opacity-0');
      popoverContent.classList.remove('opacity-100');
    }
  });
</script>
{% endcompress %}
</tbody>

tp/templates/tp/partials/_table_row.html
<th id="tpentry-{{ entry.id }}-institute" hx-get="{% url 'tp_popover_content' entry.id %}" hx-trigger="click" hx-target="#popover-content" hx-swap="innerHTML" hx-indicator=".htmx-indicator" scope="row" class="popover-trigger px-3 py-0 font-medium text-gray-900 whitespace-nowrap dark:text-white">
  <span class="flex {% if entry.not_visited %}text-red-800 dark:text-red-500{% endif %}">
    {{ entry.institute }}
  </span>
</th>